# $File: //ASP/opa/mct/iocs/MCTMSCIOC01/MCTMSCIOC01App/Makefile $
# $Revision: #1 $
# $DateTime: 2021/04/23 15:55:48 $
# Last checked in by: $Author: pozara $
#

TOP = ..
include $(TOP)/configure/CONFIG
DIRS := $(DIRS) $(filter-out $(DIRS), $(wildcard *src*))
DIRS := $(DIRS) $(filter-out $(DIRS), $(wildcard *Src*))
DIRS := $(DIRS) $(filter-out $(DIRS), $(wildcard *db*))
DIRS := $(DIRS) $(filter-out $(DIRS), $(wildcard *Db*))
include $(TOP)/configure/RULES_DIRS

# end
